### ISSUE TITLE
Tensorflow Probability compatibility

### ISSUE THREAD

**Issue by giorava** [mmtrebuchet/bpreveal#4]
Hello :) 

**Describe the bug**
I am trying to run the oskn example in bpreveal/doc/demos/osknExample.ipynb. I installed the package on our cluster and ran all the relevant preprocessing. However, the training fails because of an error associated with the incompatibility of the tensorflow-probability versions. I tried to update the package, but then I got conflicts with Keras and a bunch of new errors associated with that.

**Environment**
_If the problem is related to packages and compatibility, how exactly did you build your environment?_ 
I slightly modified buildCondaCerebro.slurm to work on our cluster. I am attaching the slurm file I use. Besides modifying the slurm directives slightly, I had to add the module load lines to avoid import errors during pybedtools installation (sqlite3 missing).

An updated version of buildCondaCerebro: [buildCondaCRG_nopaths.txt](https://github.com/user-attachments/files/18098872/buildCondaCRG_nopaths.txt)

_If the problem is with Tensorflow, can you install Tensorflow in any other way?_ I tried updating tensorflow and all the related packages to avoid conflicts. In this case, training proceeded smoothly, but I got errors during the model evaluation.

_You can list your installed packages with `conda env export`._ Attached the yml: [packages_github.txt](https://github.com/user-attachments/files/18098799/packages_github.txt)

**Data sources**
_Where can I get the data and files that you were using?_ I used the zenodo data of the original bpnet as outlined in bpreveal/doc/demos/osknExample.ipynb

**To Reproduce**
_Steps to reproduce the behavior:_ (might be cluster specific): 

1. install bpreveal with the .slurm attached (cluster specific)
2. run the preprocessing up to the training step
3. train with the train.slurm file attached (cluster specific) 

**Logs**
_Run BPReveal with DEBUG verbosity and paste the relevant logs. Attached:_ 
[installation.log](https://github.com/user-attachments/files/18098992/installation.log)
[training.log](https://github.com/user-attachments/files/18098993/training.log)

Thanks for the help <3

**Comment by mmtrebuchet** [comment]
Thanks for the detailed logs. I'll look into this and let you know. Tensorflow versions have always been hairy. @mmtrebuchet

**Comment by mmtrebuchet** [comment]
Okay, so it looks like the tensorflow-probability pip package doesn't specify the tensorflow version it needs but still only supports exactly one release at any time. Ugh. I'm currently testing a version of the buid script that uses the latest version of everything. If that passes, I'll release 5.1.0 this weekend and it should take care of the problem.

**Comment by mmtrebuchet** [comment]
@giorava I've just released 5.1.0 and it does away with the version locking. If you want to cherry pick, the relevant commit is a08c289 It should fix the issue. Irritating to learn that pybedtools is acting up AGAIN, I'll try moving that from pip to conda in the next release. If that doesn't work, I might just remove the dependency altogether and make a pure python one myself.

Version-wise, I have tensorflow 2.18.0, Keras 3.7.0, and tensorflow-probability 0.25.0, numpy 2.0.2, and numba 0.60.0.

Let me know if it's still giving you trouble and we can dig further. 
Cheers,
Charles.

**Comment by giorava** [comment]
Hey @mmtrebuchet, amazing! 
I'll try the installation next week. Thanks for this! 
Have a lovely weekend :) 
_Giorgio_

**Comment by giorava** [comment]
Hey Charles, 
I tried the new installation in the last commit, and it failed at the pybedtools step. To solve the issue, I just updated the pybedtools line in buildCondaSuite.zsh using conda for the installation: 

```
runAndCheck ${PIP_BIN} install --no-input pysam pybigwig
runAndCheck ${CONDA_BIN} install bioconda::pybedtools 
checkPackage pybedtools
checkPackage pyBigWig
checkPackage pysam 
```

For now everything is working up to the evaluation of the bias model. 
thanks for spending time on this! 
 
Have a lovely day, 
_Giorgio_

**Comment by mmtrebuchet** [comment]
Awesome! I'll switch pybedtools over to conda; as I recall I had to use pip because there wasn't a version that supported python 3.12 when I made the install script. This will probably come out with 5.2, so that could be a while.
Thanks for your help! 
Cheers,
Charles.
